import pytest

from computeedge.config.loader import load_bundled_yaml
from computeedge.services.analysis import AnalysisService


@pytest.fixture
def analysis_service():
    return AnalysisService(load_bundled_yaml("stacks.yaml"))


@pytest.mark.asyncio
async def test_classifies_placeholder_env_vars_as_required(analysis_service, fixtures_dir):
    result = await analysis_service.analyze(fixtures_dir / "sample_missing_envvars")
    # These have placeholder values (your-key-here, empty, changeme, <...>, xxx, TODO)
    assert "OPENAI_API_KEY" in result.env_vars_required
    assert "STRIPE_SECRET_KEY" in result.env_vars_required
    assert "NEXT_PUBLIC_API_URL" in result.env_vars_required


@pytest.mark.asyncio
async def test_classifies_real_defaults_as_optional(analysis_service, fixtures_dir):
    result = await analysis_service.analyze(fixtures_dir / "sample_missing_envvars")
    assert "LOG_LEVEL" in result.env_vars_optional
    # PORT is filtered as infra noise (auto-set by compose template)
    assert "PORT" not in result.env_vars_required
    assert "PORT" not in result.env_vars_optional
    assert "DEBUG" in result.env_vars_optional


@pytest.mark.asyncio
async def test_auto_generated_vars_excluded_from_required(analysis_service, fixtures_dir):
    result = await analysis_service.analyze(fixtures_dir / "sample_missing_envvars")
    # DATABASE_URL, SECRET_KEY, REDIS_URL are auto-generated by ComputeEdge
    assert "DATABASE_URL" not in result.env_vars_required
    assert "SECRET_KEY" not in result.env_vars_required
    assert "REDIS_URL" not in result.env_vars_required


@pytest.mark.asyncio
async def test_env_vars_deduplicated(analysis_service, fixtures_dir):
    result = await analysis_service.analyze(fixtures_dir / "sample_missing_envvars")
    # No duplicates in either list
    assert len(result.env_vars_required) == len(set(result.env_vars_required))
    assert len(result.env_vars_optional) == len(set(result.env_vars_optional))


@pytest.mark.asyncio
async def test_env_vars_needed_still_populated(analysis_service, fixtures_dir):
    """Backward compat: env_vars_needed still contains all var names."""
    result = await analysis_service.analyze(fixtures_dir / "sample_missing_envvars")
    assert len(result.env_vars_needed) > 0
